"""empty message

Revision ID: 8c1f252897df
Revises: b8cb40d7baef
Create Date: 2017-06-28 22:27:39.405706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c1f252897df'
down_revision = 'b8cb40d7baef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'replies', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'replies', 'thread', ['thread_id'], ['id'])
    op.create_foreign_key(None, 'thread', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'thread', type_='foreignkey')
    op.drop_constraint(None, 'replies', type_='foreignkey')
    op.drop_constraint(None, 'replies', type_='foreignkey')
    # ### end Alembic commands ###
